[package]
name = "spyplot"
version = "0.1.0"
edition = "2021"

[[example]]
name = "demo"

[[example]]
name = "demo2"

[dependencies]
bytemuck = "^1.12"
egui = "^0.31"
egui-wgpu = "^0.31"
egui_plot = "^0.31"
eframe = { version = "^0.31", features = ["wgpu"] }
